AWSTemplateFormatVersion: 2010-09-09
Resources:
  BucketAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:ListBucket'
                Resource: 'arn:aws:s3:::FileRepository'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                Resource: 'arn:aws:s3:::FileRepository'
  AccessInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref BucketAccessRole
  docEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-80861296
      InstanceType: t2.nano
      Monitoring: true
      DisableApiTermination: false
      IamInstanceProfile:
        !Ref AccessInstanceProfile
  
  FileRepository:
    Type: 'AWS::S3::Bucket'
